apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logaggregator.fullname" . }}-config
  labels:
    {{- include "logaggregator.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
