apiVersion: v1
kind: Service
metadata:
  name: {{ include "logaggregator.fullname" . }}
  labels:
    {{- include "logaggregator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.syslogUdp }}
      targetPort: syslog-udp
      protocol: UDP
      name: syslog-udp
    - port: {{ .Values.service.ports.syslogTcp }}
      targetPort: syslog-tcp
      protocol: TCP
      name: syslog-tcp
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.ports.health }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "logaggregator.selectorLabels" . | nindent 4 }}
